on:
  push:
    tags:
      - 'v*'


name: release-binary

env:
  PROJECT_NAME: pack


jobs:
  build:
    strategy:
      matrix:
        os:
          - name: macos-latest
            target: x86_64-apple-darwin
          - name: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: archive-binary
        run: ./ci/tar.sh ${{ github.ref }} ${{ matrix.os.target }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.update_url }}
          assert_path: ./${{ env.PROJECT_NAME }}-${{ github.ref }}-${{ matrix.os.target }}.tar.gz
